apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-example-monitor
  name: prometheus-example-monitor
  namespace: frontier
spec:
  endpoints:
  - interval: 30s
    port: 8080-tcp
    scheme: http
    path: /metrics2
  selector:
    matchLabels:
      app: front-test
